name: 开始每日签到

# 修正1：权限设置精简
permissions:
  actions: read
  issues: write  # 星标触发需要issue权限

# 修正2：正确的触发事件
on:
  workflow_dispatch:    # 手动触发
  schedule:             # 定时触发
    - cron: '30 1 * * *' # UTC 1:30 (北京9:30)
  issues:               # ✅ 星标触发正确写法
    types: [opened]     # 开启issue时触发（通过自动发issue实现星标触发）

# 修正3：标准工作目录设定
jobs:
  checkin:
    runs-on: ubuntu-latest
    
    # 修正4：缓存依赖加速执行
    env:
      PYTHON_VERSION: '3.10'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 新增：Python环境配置
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      # 新增：安装Python依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 修正5：添加超时处理
      - name: 执行签到
        timeout-minutes: 3
        run: python glados.py
        env: 
          GLADOS_COOKIE: "${{ secrets.GLADOS_COOKIE }}"
          PUSHPLUS_TOKEN: "${{ secrets.PUSHPLUS_TOKEN }}"
      
      # 修正6：保持活跃替换为有效Action
      - name: Keep Active
        if: ${{ always() }}
        uses: gautamkrishnar/keepalive-workflow@v1.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
