name: 开始每日签到

permissions:
  contents: write   # 关键权限
  actions: read

on:
  workflow_dispatch:   # 手动触发
  schedule:            # 定时触发（UTC 1:30 = 北京9:30）
    - cron: '30 1 * * *'
  watch:               # 标星触发
    types: [started]   # 用户给仓库加⭐时激活

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # 安全版本

      - name: 执行签到
        run: python glados.py
        env: 
          GLADOS_COOKIE: "${{ secrets.GLADOS_COOKIE }}"
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
      - uses: gautamkrishnar/keepalive-workflow@master  
